/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectuasdisprog;

/**
 *
 * @author Asus
 */
public class ChooseSubMenu extends javax.swing.JFrame {

    /**
     * Creates new form ChooseSubMenu
     */
    public ChooseSubMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTicket = new javax.swing.JButton();
        btnParking = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnClaim = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        jLabel1.setText("Car Parking Reservation");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(590, 350, 244, 30);

        btnTicket.setBackground(new java.awt.Color(0, 204, 0));
        btnTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectuasdisprog/images/attr.png"))); // NOI18N
        btnTicket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51)));
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });
        getContentPane().add(btnTicket);
        btnTicket.setBounds(140, 170, 170, 170);

        btnParking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectuasdisprog/images/car.png"))); // NOI18N
        btnParking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        btnParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParkingActionPerformed(evt);
            }
        });
        getContentPane().add(btnParking);
        btnParking.setBounds(620, 170, 170, 170);

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 40)); // NOI18N
        jLabel3.setText("What Are You Looking For?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 90, 580, 60);

        btnClaim.setBackground(new java.awt.Color(0, 204, 0));
        btnClaim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectuasdisprog/images/tiket.png"))); // NOI18N
        btnClaim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51)));
        btnClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaimActionPerformed(evt);
            }
        });
        getContentPane().add(btnClaim);
        btnClaim.setBounds(380, 170, 170, 170);

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        jLabel4.setText("Claim Ticket");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 340, 129, 60);

        btnBack.setBackground(new java.awt.Color(204, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnBack.setText("LOG OUT");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(750, 40, 100, 40);

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        jLabel5.setText("Attraction Tickets");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 340, 176, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectuasdisprog/images/choose-sub.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 940, 510);

        labelUsername.setText("jLabel5");
        getContentPane().add(labelUsername);
        labelUsername.setBounds(10, 20, 51, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParkingActionPerformed
        // TODO add your handling code here:
        String username = labelUsername.getText();
        UIParkingReservation upr = new UIParkingReservation();
        upr.labelNama.setText(username);
        upr.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnParkingActionPerformed

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        // JANGAN LUPA KIRIM VALUE USERNAME KE TIAP FORM BIAR BISA ADD DATA
        String username = labelUsername.getText();
        UIAcara ua = new UIAcara();
        ua.LabelUser.setText(username);
        ua.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaimActionPerformed
        // TODO add your handling code here:
        UIClaimTicket uclaim = new UIClaimTicket(labelUsername.getText());
//        uclaim.labelNama.setText(labelUsername.getText());
        uclaim.setVisible(true);
        
    }//GEN-LAST:event_btnClaimActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseSubMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseSubMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseSubMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseSubMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseSubMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClaim;
    private javax.swing.JButton btnParking;
    private javax.swing.JButton btnTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel labelUsername;
    // End of variables declaration//GEN-END:variables
}
