/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectuasdisprog;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import static java.lang.System.in;
import static java.lang.System.out;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Leon
 */
public class DetailPemesananTiket extends javax.swing.JFrame implements Runnable {

    Socket clientSocket;
    Thread t;
    DataOutputStream out;
    BufferedReader in;
    
    public DetailPemesananTiket() {
        initComponents();
        try {
            initComponents();
            //UNTUK MULTITHREADING TCP
            clientSocket = new Socket("localhost", 8282);
            if (t == null) {
                t = new Thread(this, "Client");
                t.start();
            }
            //declare untuk in (terima message) dan out (kirim message)
            out = new DataOutputStream(clientSocket.getOutputStream());
            in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
        } catch (Exception ex) {
            System.out.println("Error di Detail Pemesanan");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lokasi = new javax.swing.JLabel();
        labelLokasi = new javax.swing.JLabel();
        harga1 = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        jenis = new javax.swing.JLabel();
        labelJenis = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        LabelEvents = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        buttonBayar = new javax.swing.JButton();
        rp = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonBatal = new javax.swing.JButton();
        labelUsername1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 650));
        getContentPane().setLayout(null);

        lokasi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(lokasi);
        lokasi.setBounds(190, 440, 210, 25);

        labelLokasi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelLokasi.setText("Lokasi");
        getContentPane().add(labelLokasi);
        labelLokasi.setBounds(40, 440, 70, 25);

        harga1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        harga1.setText("                                      ");
        getContentPane().add(harga1);
        harga1.setBounds(230, 380, 350, 32);

        labelHarga.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelHarga.setText("Harga");
        getContentPane().add(labelHarga);
        labelHarga.setBounds(40, 380, 70, 30);

        total.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(total);
        total.setBounds(180, 540, 130, 25);

        nama.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(nama);
        nama.setBounds(190, 230, 200, 25);

        tanggal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(tanggal);
        tanggal.setBounds(190, 330, 250, 30);

        labelTanggal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTanggal.setText("Tanggal");
        getContentPane().add(labelTanggal);
        labelTanggal.setBounds(40, 330, 100, 30);

        jenis.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jenis);
        jenis.setBounds(190, 270, 230, 40);

        labelJenis.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelJenis.setText("Jenis");
        getContentPane().add(labelJenis);
        labelJenis.setBounds(40, 270, 100, 40);

        labelNama.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelNama.setText("Nama");
        getContentPane().add(labelNama);
        labelNama.setBounds(40, 230, 70, 25);

        LabelEvents.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabelEvents.setText("DETAIL PEMESANAN");
        getContentPane().add(LabelEvents);
        LabelEvents.setBounds(10, 50, 370, 48);

        id.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(id);
        id.setBounds(190, 130, 200, 25);

        labelID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelID.setText("ID");
        getContentPane().add(labelID);
        labelID.setBounds(40, 130, 70, 25);

        buttonBayar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonBayar.setForeground(new java.awt.Color(0, 204, 51));
        buttonBayar.setText("BAYAR");
        buttonBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBayarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBayar);
        buttonBayar.setBounds(470, 540, 120, 40);

        rp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rp.setText("Rp");
        getContentPane().add(rp);
        rp.setBounds(190, 380, 40, 32);

        labelUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(labelUser);
        labelUser.setBounds(190, 180, 110, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectuasdisprog/images/logo tiket kotak.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 20, 240, 120);

        buttonBatal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonBatal.setForeground(new java.awt.Color(204, 0, 0));
        buttonBatal.setText("BATAL");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBatal);
        buttonBatal.setBounds(330, 540, 120, 40);

        labelUsername1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelUsername1.setText("Username");
        getContentPane().add(labelUsername1);
        labelUsername1.setBounds(40, 180, 110, 25);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBayarActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin melanjutkan pembayaran?",
                "Konfirmasi Pembayaran", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            int hargaTiket = Integer.parseInt(harga1.getText());
            String username = labelUser.getText();
            String namaAcara = this.nama.getText();
            String idPesanan = id.getText();
            String message = "Bayar:" + hargaTiket + ":" + username + ":" + namaAcara + ":" + idPesanan;
            sendMessage(message);
            String chatServer = "";
            try {
                chatServer = in.readLine();
            } catch (IOException ex) {
                Logger.getLogger(DetailPemesananTiket.class.getName()).log(Level.SEVERE, null, ex);
            }
                JOptionPane.showMessageDialog(this, chatServer);
                ChooseSubMenu ch = new ChooseSubMenu();
                ch.labelUsername.setText(username);
                ch.setVisible(true);
                this.dispose();
        }
        
        
    }//GEN-LAST:event_buttonBayarActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        ChooseSubMenu ch = new ChooseSubMenu();
        ch.setVisible(true);
        ch.labelUsername.setText(this.labelUser.getText());
        this.dispose();
    }//GEN-LAST:event_buttonBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailPemesananTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailPemesananTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailPemesananTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailPemesananTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailPemesananTiket().setVisible(true);
            }
        });
    }

    public void sendMessage(String s) //METHOD UTK MENGIRIM PESAN KE SERVER
    {
        try {
            out.writeBytes(s + "\n");
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEvents;
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonBayar;
    public javax.swing.JLabel harga1;
    public javax.swing.JLabel id;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jenis;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelJenis;
    private javax.swing.JLabel labelLokasi;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTanggal;
    public javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelUsername1;
    public javax.swing.JLabel lokasi;
    public javax.swing.JLabel nama;
    private javax.swing.JLabel rp;
    public javax.swing.JLabel tanggal;
    public javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
@Override
    public void run() {

        while (true) {
            try {

            } catch (Exception e) {
            }
        }

    }
}
