/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectuasdisprog;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class MainMenu extends javax.swing.JFrame implements Runnable {
    
    
    
    
    /**
     * Creates new form MainMenu
     */
    Socket clientSocket;
    Thread t;
    DataOutputStream out;
    BufferedReader in;
    public MainMenu() {
        try {
            initComponents();
            //UNTUK MULTITHREADING TCP
            //clientSocket = new Socket("localhost", 8282);
            clientSocket = new Socket("localhost",8282);
            if (t == null) {
                t = new Thread(this, "Client");
                t.start();
            }
            //declare untuk in (terima message) dan out (kirim message)
            out = new DataOutputStream(clientSocket.getOutputStream());
            in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
        } catch (Exception ex) {
            System.out.println("Error di Login");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1005, 590));
        setSize(new java.awt.Dimension(950, 534));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 72)); // NOI18N
        jLabel4.setText("buoy-buoyant!");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 120, 580, 100);

        jButtonLogin.setBackground(new java.awt.Color(184, 213, 136));
        jButtonLogin.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin);
        jButtonLogin.setBounds(640, 320, 110, 40);

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel8.setText("Password :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(210, 280, 100, 20);

        txtUsername.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        getContentPane().add(txtUsername);
        txtUsername.setBounds(330, 220, 420, 40);

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel6.setText("Username :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 230, 140, 20);

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        jLabel7.setText("Dont Have Any Account?");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 360, 240, 20);

        txtPassword.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        getContentPane().add(txtPassword);
        txtPassword.setBounds(330, 270, 420, 40);

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Register");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(380, 360, 110, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectuasdisprog/images/home.png"))); // NOI18N
        jLabel1.setText("hahahaha");
        jLabel1.setMinimumSize(new java.awt.Dimension(950, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        try {
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        //message itu command[0] merupakan perintah ttg fungsi apa yg mau dilakukan
        String message = "LOGIN:"+username + ":" + password;

        // Send login info to the server (PAKAI METHOD SEND MESSAGE YG SUDAH DIBUAT)
        sendMessage(message);

        // Receive response from the server
        String chatServer = in.readLine();
       
        if ("LOGIN BERHASIL".equals(chatServer)) {
            JOptionPane.showMessageDialog(rootPane, "Selamat Datang di Aplikasi buoy-buoyant!");
            ChooseSubMenu cs = new ChooseSubMenu();
            cs.labelUsername.setText(username);
            cs.setVisible(true);
            this.dispose();
        
        } else {
            JOptionPane.showMessageDialog(rootPane, "LOGIN GAGAL. Username/Password Anda Salah");
        }
        
    } catch (Exception ex) {
        System.out.println("Error di login: " + ex.getMessage());
    }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        RegisterPage rp = new RegisterPage();
        rp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    public void GetMessage()
    {
        try {
            String message = in.readLine();
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        @Override
    public void run() {

        while (true) {
//            try 
//            {
//              GetMessage();
//            } catch (Exception e) {
//            }
        }

    }
    
    public void sendMessage(String s) //METHOD UTK MENGIRIM PESAN KE SERVER
    {
        try {
            out.writeBytes(s + "\n");
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
