/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectuasdisprog;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class RegisterPage extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form RegisterPage
     */
    Socket clientSocket;
    Thread t;
    DataOutputStream out;
    BufferedReader in;
    
    public RegisterPage() {
        try {
            initComponents();
            //UNTUK MULTITHREADING TCP
            clientSocket = new Socket("localhost", 8282);
            if (t == null) {
                t = new Thread(this, "Client");
                t.start();
            }
            //declare untuk in (terima message) dan out (kirim message)
            out = new DataOutputStream(clientSocket.getOutputStream());
            in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
        } catch (Exception ex) {
            System.out.println("Error di Register");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jTextFieldUsername = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel3.setText("REGISTER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 90, 300, 62);

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel4.setText("Name :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 180, 70, 20);

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel5.setText("Username :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 280, 110, 20);

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel6.setText("Email :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 230, 70, 20);

        jTextFieldPassword.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        getContentPane().add(jTextFieldPassword);
        jTextFieldPassword.setBounds(300, 330, 470, 26);

        jTextFieldUsername.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        getContentPane().add(jTextFieldUsername);
        jTextFieldUsername.setBounds(300, 280, 470, 26);

        jTextFieldNama.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        getContentPane().add(jTextFieldNama);
        jTextFieldNama.setBounds(300, 180, 470, 26);

        jTextFieldEmail.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(300, 230, 470, 26);

        jButtonRegister.setBackground(new java.awt.Color(184, 213, 136));
        jButtonRegister.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister);
        jButtonRegister.setBounds(650, 370, 120, 40);

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel7.setText("Password :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 330, 100, 20);

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        jLabel8.setText("Already have account?");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 430, 180, 20);

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Login");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(350, 430, 110, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectuasdisprog/images/basic.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 910, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        try{
            String nama = jTextFieldNama.getText();
            String email = jTextFieldEmail.getText();
            String username = jTextFieldUsername.getText();
            String password = jTextFieldPassword.getText();
            
            String message = "REGISTER:"+nama+ ":" + email + ":" + username + ":" + password;
            
            sendMessage(message);
            
            String chatServer = in.readLine();
            
            if(chatServer.equals("REGISTER BERHASIL"))
            {
                JOptionPane.showMessageDialog(this, chatServer);
                MainMenu mm = new MainMenu();
                mm.setVisible(true);
                this.setVisible(false);
                this.dispose();
            }
            else
            {
                 JOptionPane.showMessageDialog(this, chatServer);
            }
            
        }
        catch(Exception ex){
            System.out.println("Error di Register " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }
    
    
    @Override
    public void run() {

        while (true) {
            try 
            {

            } catch (Exception e) {
            }
        }

    }
    
    public void sendMessage(String s) //METHOD UTK MENGIRIM PESAN KE SERVER
    {
        try {
            out.writeBytes(s + "\n");
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
