/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectuasdisprog;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.time.LocalDate;
import static java.time.LocalDate.of;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class UIParkingReservation extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form UIParkingReservation
     */
    Socket clientSocket;
    Thread t;
    DataOutputStream out;
    BufferedReader in;
    public UIParkingReservation() {
        try {
            initComponents();
           
            //UNTUK MULTITHREADING TCP
            clientSocket = new Socket("localhost", 8282);
            if (t == null) {
                t = new Thread(this, "Client");
                t.start();
            }
            
             //declare untuk in (terima message) dan out (kirim message)
            out = new DataOutputStream(clientSocket.getOutputStream());
            in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            //kirim data minta daftar tempat parkir yg tersedia
            sendMessage("BacaParkiran:");
            //terima data parkiran yang dimiliki
            String message = in.readLine();
            String[]tempatParkir = message.split(":"); //split message dgn menggunakan : utk mendapatkan daftar semua tempat parkir
            for(String lokasi : tempatParkir)
            {
                jComboBoxTempatParkir.addItem(lokasi); //masukkan setiap lokasi ke combobox
            }
            
        } catch (Exception ex) {
            System.out.println("Error di reservasi parkir");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonBook = new javax.swing.JButton();
        txtTanggal = new javax.swing.JTextField();
        jButtonKlikTgl = new javax.swing.JButton();
        jComboBoxTempatParkir = new javax.swing.JComboBox<>();
        labelLokasi = new javax.swing.JLabel();
        labelLokasi1 = new javax.swing.JLabel();
        labelSelectedLot = new javax.swing.JLabel();
        labelLokasi3 = new javax.swing.JLabel();
        labelLokasi4 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelTanggalPesan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNoPlat = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 40)); // NOI18N
        jLabel3.setText("RESERVASI LOT PARKIR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 30, 520, 70);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel2.setText("RINCIAN RESERVASI");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(660, 190, 240, 20);

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel5.setText("Tanggal Pesan :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 170, 150, 30);

        jButtonBook.setBackground(new java.awt.Color(0, 204, 0));
        jButtonBook.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        jButtonBook.setText("Book");
        jButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBook);
        jButtonBook.setBounds(840, 390, 80, 30);

        txtTanggal.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtTanggal.setEnabled(false);
        getContentPane().add(txtTanggal);
        txtTanggal.setBounds(180, 170, 270, 30);

        jButtonKlikTgl.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButtonKlikTgl.setText("Klik");
        jButtonKlikTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKlikTglActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKlikTgl);
        jButtonKlikTgl.setBounds(460, 170, 70, 30);

        jComboBoxTempatParkir.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jComboBoxTempatParkir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTempatParkirActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTempatParkir);
        jComboBoxTempatParkir.setBounds(180, 130, 270, 30);

        labelLokasi.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        labelLokasi.setText("Lot yang dipilih :");
        getContentPane().add(labelLokasi);
        labelLokasi.setBounds(580, 320, 130, 20);

        labelLokasi1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelLokasi1.setText("TUNJUNGAN PLAZA");
        getContentPane().add(labelLokasi1);
        labelLokasi1.setBounds(580, 230, 190, 20);

        labelSelectedLot.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        labelSelectedLot.setText("BELUM DIPILIH");
        getContentPane().add(labelSelectedLot);
        labelSelectedLot.setBounds(720, 320, 170, 20);

        labelLokasi3.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        labelLokasi3.setText("Tanggal Pesan :");
        getContentPane().add(labelLokasi3);
        labelLokasi3.setBounds(590, 290, 120, 20);

        labelLokasi4.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        labelLokasi4.setText("Username :");
        getContentPane().add(labelLokasi4);
        labelLokasi4.setBounds(620, 260, 90, 20);

        labelNama.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        labelNama.setText("Tororo");
        getContentPane().add(labelNama);
        labelNama.setBounds(720, 260, 60, 20);

        labelTanggalPesan.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        labelTanggalPesan.setText("NULL");
        getContentPane().add(labelTanggalPesan);
        labelTanggalPesan.setBounds(720, 290, 90, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectuasdisprog/images/polos.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 105, 159), 4));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(560, 170, 360, 210);

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel7.setText("No.Plat :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 210, 70, 30);

        jButtonCari.setBackground(new java.awt.Color(0, 204, 0));
        jButtonCari.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCari);
        jButtonCari.setBounds(430, 210, 100, 30);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jpanel1.setBackground(new java.awt.Color(255, 244, 231));

        javax.swing.GroupLayout jpanel1Layout = new javax.swing.GroupLayout(jpanel1);
        jpanel1.setLayout(jpanel1Layout);
        jpanel1Layout.setHorizontalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );
        jpanel1Layout.setVerticalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jpanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 260, 510, 270);

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel8.setText("Lokasi :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 130, 70, 30);

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel9.setText("Lokasi :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 130, 70, 30);

        txtNoPlat.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        getContentPane().add(txtNoPlat);
        txtNoPlat.setBounds(180, 210, 240, 30);

        btnBack.setBackground(new java.awt.Color(255, 51, 51));
        btnBack.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(840, 10, 80, 30);

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectuasdisprog/images/ReserveCar.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 930, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed
        
        try {
            LocalDate selectedDate = LocalDate.parse(txtTanggal.getText());
            if(selectedDate.isAfter(LocalDate.now()))
            {
                if (txtNoPlat.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Silahkan isi nomor plat kendaraan Anda!");

                } else {
                    //setiap kali selesai add data jgn lupa refresh lot parkir
                    String lokasi = jComboBoxTempatParkir.getSelectedItem().toString();
                    String tglPesan = txtTanggal.getText();
                    String noplat = txtNoPlat.getText();
                    String lot = labelSelectedLot.getText();
                    String username = labelNama.getText();

                    String message = "BOOK:" + lokasi + ":" + tglPesan + ":" + noplat + ":" + lot + ":" + username;
                    sendMessage(message);
                    String chatServer = in.readLine();

                    if (chatServer.equals("BOOK BERHASIL")) {
                        JOptionPane.showMessageDialog(this, chatServer);
                        RefreshParkingLot();
                    } else {
                        JOptionPane.showMessageDialog(this, chatServer);
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Anda hanya bisa memesan parkiran minimal H-1");
            }
           
        } catch (IOException ex) {
            Logger.getLogger(UIParkingReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBookActionPerformed

    private void jButtonKlikTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKlikTglActionPerformed
        // TODO add your handling code here:
        DatePicker dp = new DatePicker(this);
        dp.displayDate();
        txtTanggal.setText(dp.setPickedDate());
        labelTanggalPesan.setText(dp.setPickedDate());
    }//GEN-LAST:event_jButtonKlikTglActionPerformed

    private void jComboBoxTempatParkirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTempatParkirActionPerformed
        String tempatParkir = jComboBoxTempatParkir.getSelectedItem().toString();
        labelLokasi1.setText(tempatParkir);
    }//GEN-LAST:event_jComboBoxTempatParkirActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
       // TODO add your handling code here:
       if(txtTanggal.getText().equals(""))
       {
           JOptionPane.showMessageDialog(this, "Silahkan pilih tanggal reservasi Anda!");
       }
       else
       {
          RefreshParkingLot(); //buat refresh parking lot setiap kali ganti tanggal atau bru insert data atau apapun lah   
       }
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        String username = labelNama.getText();
        ChooseSubMenu ch = new ChooseSubMenu();
        ch.labelUsername.setText(username);
        ch.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed
    private void RefreshParkingLot()
    {
        try {
            //KIRIM MESSAGE KE SERVER UTK BACA KAPASITAS DR COMBOBOX YG DIPILIH
            String lokasiParkir = jComboBoxTempatParkir.getSelectedItem().toString();
            jpanel1.removeAll(); //hapus semua komponen yang ada di panel saat ini
            jpanel1.setLayout(new GridLayout(50,50)); // Set layout for jPanel1
            //KIRIM PESAN UTK BACA BRP JMLH KAPASITAS DR TEMPAT PARKIR YG DIPILIH
            //CARI JUGA AVAILIBILITY DR LOT PARKIR PADA TGL TSB
            String tanggal = txtTanggal.getText();
            //SEND MESSAGE KE SERVER
            String messageToServer = "CekLotParkir:"+lokasiParkir+":"+tanggal;
            sendMessage(messageToServer);
            String msgFromServer = in.readLine();
            String[] msgSplit = msgFromServer.split(":");
            int capacity = Integer.parseInt(msgSplit[0]);
             ArrayList<Integer>listLotTerisi=new ArrayList<>(); //masukin sini buat nnti dicompare yg udh keisi nnti gbs dipencet
            //hasil splitting kedua menyimpan list lot yg udh terisi
            if(msgSplit.length>1)
            {
                String lotTerisi = msgSplit[1];
                String[] lotDipakai = lotTerisi.split(","); //ini pecahan dr kumpulan lot yg terisi
                if (lotDipakai.length > 0) {
                    for (String lot : lotDipakai) {
                        int lotMobil = Integer.parseInt(lot);
                        listLotTerisi.add(lotMobil);
                    }
                }
            }   
            for (int i = 0; i <capacity; i++) 
            {
                JButton button = new JButton(Integer.toString(i + 1));
                button.setBackground(Color.GREEN);
                //beri tanda mana saja element yang warnanya sdh terisi >> SO FAR MASIH MINUS KLO KLIK BUTTON CARI 2X, MAKA DIA ERROR
                if(!listLotTerisi.isEmpty())
                {
                    if(listLotTerisi.contains(i+1))
                    {
                        button.setEnabled(false);
                    }
                }
                button.setPreferredSize(new Dimension(50, 30)); //buat ngatur size tempat parkirnya
                jpanel1.add(button);
                
                //atur supaya setiap kali button diklik, maka value di textbox akan terupdate
                button.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e)
                    {
                        //klo tombol button diklik, update value pada semua :))
                        //set nama tempat parkir, dll sesuai yg diinput
                        //isi lot sesuai button yg diklik
                        labelSelectedLot.setText(button.getText());
                    }
                });
                jpanel1.revalidate(); //digunakan untuk memvalidasi bahwa ada komponen yang baru ditambahkan ke dalam panel
                jpanel1.repaint();//digunakan untuk memastikan bahwa ada perubahan dalam komponen, jd klo ada perubahan maka diupdate dgn komponen yang baru   
            }
        } catch (IOException ex) {
            Logger.getLogger(UIParkingReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIParkingReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIParkingReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIParkingReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIParkingReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIParkingReservation().setVisible(true);
            }
        });
    }
    public void sendMessage(String s) //METHOD UTK MENGIRIM PESAN KE SERVER
    {
        try {
            out.writeBytes(s + "\n");
        } catch (Exception e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButtonBook;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonKlikTgl;
    private javax.swing.JComboBox<String> jComboBoxTempatParkir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanel1;
    private javax.swing.JLabel labelLokasi;
    private javax.swing.JLabel labelLokasi1;
    private javax.swing.JLabel labelLokasi3;
    private javax.swing.JLabel labelLokasi4;
    public javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelSelectedLot;
    private javax.swing.JLabel labelTanggalPesan;
    private javax.swing.JTextField txtNoPlat;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() 
    {
    }
}
